### ISSUE TITLE
`basedpyright-server` crashes due to it not finding `nodejs_wheel` 

### ISSUE THREAD

**Issue by daniel-hernandez-sony** [LoganWalls/basedpyright-nix#2]
(thank you very much for your work!)

I use `neovim` as my editor and want to use `basedpyright` as a python lsp.  Unfortunately, it is crashing due to not having a package installed as part of its python installation.

### Installation

I use flakes with `basedpyright-nix` as an input, and I use `basedpyright-nix`'s `default` package as part of my home-manager's `home.packages`. 

### Error:
When neovim calls `basedpyright-langserver` the latter command crashes due to it's python not having the [nodejs_wheel](https://pypi.org/project/nodejs-wheel/) package installed. Error (look at the end of the line):
```
 [ERROR][2024-05-22 10:51:43] .../vim/lsp/rpc.lua:770	"rpc"	"/nix/store/agr77zs82iiwapf1pidnnwj6r3c6pky7-python3.11-basedpyright-1.12.2/bin/basedpyright-langserver"	"stderr"	"Traceback (most recent call last):\n  File \"/nix/store/agr77zs82iiwapf1pidnnwj6r3c6pky7-python3.11-basedpyright-1.12.2/bin/.basedpyright-langserver-wrapped\", line 6, in <module>\n    from basedpyright.langserver import main\n  File \"/nix/store/agr77zs82iiwapf1pidnnwj6r3c6pky7-python3.11-basedpyright-1.12.2/lib/python3.11/site-packages/basedpyright/langserver.py\", line 3, in <module>\n    from basedpyright.run_node import run\n  File \"/nix/store/agr77zs82iiwapf1pidnnwj6r3c6pky7-python3.11-basedpyright-1.12.2/lib/python3.11/site-packages/basedpyright/run_node.py\", line 6, in <module>\n    from nodejs_wheel.executable import node\nModuleNotFoundError: No module named 'nodejs_wheel'\n"
```

Do you also see this issue?

**Comment by LoganWalls** [comment]
Hi! Thank you for the report.

So I'm not sure I have a good grasp of this issue, but it looks like `basedpyright` is now being [packaged officially in nixpkgs](https://github.com/NixOS/nixpkgs/pull/308503#pullrequestreview-2073754389) (it has not been merged at the time of writing, but looks like it should be merged within a couple of days). That makes this flake unnecessary I think. I would recommend using that, unless there's some reason you would prefer this flake (if there's a good reason please let me know and I'll see if I can fix the flake). 😄

**Comment by daniel-hernandez-sony** [comment]
I saw as well that some one packaged it officially. I shall try that instead as it finishes merging. Thank you for having put this flake up before it went into nixpkgs. People like you make using nix better!
